# This workflow calls the master E2E workflow with custom variables
name: UI-Pull-Request_RM_head_2.8

on:
  pull_request:
    branches: [ main ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths-ignore:
      - 'README.md'

jobs:
  ui:
    uses: ./.github/workflows/master-e2e.yaml
    secrets:
      credentials: ${{ secrets.GCP_CREDENTIALS }}
      pat_token: ${{ secrets.SELF_HOSTED_RUNNER_PAT_TOKEN }}
      rancher_password: ${{ secrets.RANCHER_PASSWORD }}
      gitlab_private_user: ${{ secrets.GITLAB_PRIVATE_USER }}
      gitlab_private_pwd: ${{ secrets.GITLAB_PRIVATE_PWD }}
      bitbucket_private_user: ${{ secrets.BITBUCKET_PRIVATE_USER }}
      bitbucket_private_pwd: ${{ secrets.BITBUCKET_PRIVATE_PWD }}
      gh_private_user: ${{ secrets.GH_PRIVATE_USER }}
      gh_private_pwd: ${{ secrets.GH_PRIVATE_PWD }}
      azure_private_user: ${{ secrets.AZURE_PRIVATE_USER }}
      azure_private_pwd: ${{ secrets.AZURE_PRIVATE_PWD }}
      rsa_private_key_qa: ${{ secrets.RSA_PRIVATE_KEY_QA }}
      rsa_public_key_qa: ${{ secrets.RSA_PUBLIC_KEY_QA }}
      qase_api_token: ${{ secrets.QASE_API_TOKEN }}
    with:
      test_description: "CI test for PR#${{ github.event.pull_request.number }} with K3s"
      cluster_name: cluster-k3s
      # WARNING, VALUES BELOW ARE HARDCODED FOR RUNS SCHEDULED BY PULL_REQUEST EVENT
      destroy_runner: true
      upstream_cluster_version: 'v1.28.8+k3s1'
      rancher_version: 'latest/devel/2.8'
      # If qase_run_id is none the run is getting deleted in QASE
      qase_run_id: 'none'
      grep_test_by_tag: '@login @p0 @p1'
